import React from "react";
import { Mic, Bot, MessageSquareText, Timer, Volume2 } from "lucide-react";
import { Briefcase, ThumbsUp } from "lucide-react";
// import { BotMessageSquare } from "lucide-react";
// import { BatteryCharging } from "lucide-react";
// import { Fingerprint } from "lucide-react";
// import { ShieldHalf } from "lucide-react";
// import { PlugZap } from "lucide-react";
// import { GlobeLock } from "lucide-react";

import user1 from "../assets/profile-pictures/user1.jpg";
import user2 from "../assets/profile-pictures/user2.jpg";
import user3 from "../assets/profile-pictures/user3.jpg";
import user4 from "../assets/profile-pictures/user4.jpg";
import user5 from "../assets/profile-pictures/user5.jpg";
import user6 from "../assets/profile-pictures/user6.jpg";

export const navItems = [
  { label: "Home", href: "#" },
  { label: "How It Works", href: "#howitworks" },
  { label: "Features", href: "#features" },
];

export const features = [
  {
    title: "Voice-to-Text",
    description:
      "Speak your answers naturally. We convert them into text using speech recognition.",
    icon: <Mic className="w-8 h-8 text-blue-600" />,
  },
  {
    title: "AI Question Generation",
    description:
      "Get role-specific technical questions generated by powerful AI.",
    icon: <Bot className="w-8 h-8 text-green-600" />,
  },
  {
    title: "Smart Feedback",
    description:
      "Receive direct, helpful feedback on your responses — no fluff, just value.",
    icon: <MessageSquareText className="w-8 h-8 text-yellow-600" />,
  },
  {
    title: "Real-time Evaluation",
    description:
      "Your answers are evaluated instantly to keep your momentum going.",
    icon: <Timer className="w-8 h-8 text-purple-600" />,
  },
  {
    title: "Professional TTS Voice",
    description:
      "Listen to feedback in a natural, professional voice for better learning.",
    icon: <Volume2 className="w-8 h-8 text-pink-600" />,
  },
];

export const howItWorks = [
  {
    title: "Choose Role & Skills",
    description:
      "Select the job title and relevant skills you're preparing for.",
    icon: <Briefcase className="w-8 h-8 text-blue-600" />,
  },
  {
    title: "Answer via Voice",
    description: "Speak your answer like you would in a real interview.",
    icon: <Mic className="w-8 h-8 text-green-600" />,
  },
  {
    title: "Get AI Feedback",
    description: "Receive detailed, helpful evaluation instantly from our AI.",
    icon: <ThumbsUp className="w-8 h-8 text-yellow-600" />,
  },
];